const presentSimple = [["I eat breakfast every morning.", 
"She plays the piano beautifully.", 
"We live in a big house.", 
"They go to school together.", 
"He speaks English fluently.", 
"The sun rises in the east.", 
"Dogs bark loudly.", 
"Birds sing in the morning.", 
"The Earth revolves around the sun.", 
"We drink coffee in the evening.", 
"It rains often in this city.", 
"I love chocolate ice cream.", 
"She works in an office.", 
"They visit their grandparents regularly.", 
"The train arrives at 9 AM.", 
"He watches movies on weekends.", 
"Cats chase mice.", 
"We wear uniforms to school.", 
"The teacher explains the lesson.", 
"The river flows smoothly.", 
"I walk to the park every day.", 
"The company produces quality products.", 
"She likes to read novels.", 
"They enjoy playing video games.", 
"The clock ticks loudly.", 
"It snows in winter.", 
"We listen to music in the car.", 
"He brushes his teeth twice a day.", 
"The cat sleeps on the couch.", 
"I run in the park for exercise.", 
"Birds build nests in trees.", 
"The store opens at 8 AM.", 
"She studies for exams.", 
"They swim in the pool.", 
"We drive to work together.", 
"The baby laughs a lot.", 
"He tells interesting stories.", 
"The computer works perfectly.", 
"I always forget my keys.", 
"She buys groceries every Sunday.", 
"They grow vegetables in the garden.", 
"We celebrate birthdays with cake.", 
"It gets dark early in winter.", 
"He climbs mountains for fun.", 
"The sun sets in the west.", 
"I teach English to students.", 
"Dogs wag their tails when happy.", 
"She plays soccer after school.", 
"We visit the beach in the summer.", 
"It tastes delicious.", 
"He exercises at the gym.", 
"They take the bus to work.", 
"I paint landscapes.", 
"The kids enjoy playing outside.", 
"She always wears a smile.", 
"We participate in community events.", 
"The moon shines at night.", 
"I write poems in my free time.", 
"Birds migrate in winter.", 
"He fixes cars for a living.", 
"They enjoy hiking in the mountains.", 
"We attend family gatherings.", 
"She practices yoga daily.", 
"The company hires new employees.", 
"I clean my room on weekends.", 
"It smells wonderful in the kitchen.", 
"The baby crawls on the floor.", 
"They play board games together.", 
"We recycle plastic bottles.", 
"He tells jokes to make people laugh.", 
"The train departs at 6 PM.", 
"I speak Spanish and English.", 
"She takes photographs of nature.", 
"We visit the museum occasionally.", 
"The cat purrs when petted.", 
"The river freezes in winter.", 
"I volunteer at the local shelter.", 
"They eat dinner at 7 PM.", 
"We walk in the park after dinner.", 
"She practices the piano daily.", 
"The clock ticks loudly.", 
"I sing in the shower.", 
"Birds build nests in spring.", 
"He enjoys watching sports.", 
"They visit relatives during holidays.", 
"We plant flowers in the garden.", 
"She reads books before bedtime.", 
"It rains during the monsoon.", 
"I work on projects at the office.", 
"The children play in the playground.", 
"Dogs fetch the ball.", 
"We ride bikes in the park.", 
"The company produces eco-friendly products.", 
"She exercises for good health.", 
"They explore new places on vacations.", 
"I enjoy learning new things.", 
"It gets hot in the summer.", 
"We take photos on special occasions.", 
"The sun gives us light.", 
"He greets everyone with a smile."], ["I don't eat meat.", 
"She doesn't play the guitar.", 
"We don't have a car.", 
"They don't watch TV in the morning.", 
"He doesn't speak French.", 
"The sun doesn't set in the east.", 
"Dogs don't meow.", 
"Birds don't fly at night.", 
"The Earth doesn't stand still.", 
"We don't drink soda.", 
"It doesn't snow in summer.", 
"I don't dislike chocolate ice cream.", 
"She doesn't work on weekends.", 
"They don't skip classes.", 
"The train doesn't arrive early.", 
"He doesn't dislike action movies.", 
"Cats don't bark.", 
"We don't wear hats indoors.", 
"The teacher doesn't ignore questions.", 
"The river doesn't flow uphill.", 
"I don't run marathons.", 
"The company doesn't cut corners.", 
"She doesn't hate rainy days.", 
"They don't avoid challenges.", 
"The clock doesn't go counterclockwise.", 
"It doesn't rain in the desert.", 
"We don't listen to heavy metal.", 
"He doesn't forget appointments.", 
"The cat doesn't hate the vacuum cleaner.", 
"I don't drive recklessly.", 
"Birds don't dislike trees.", 
"The store doesn't close late.", 
"She doesn't procrastinate.", 
"They don't dislike swimming.", 
"We don't fly kites indoors.", 
"The baby doesn't cry all night.", 
"He doesn't tell boring stories.", 
"The computer doesn't crash often.", 
"I don't always remember names.", 
"She doesn't dislike spicy food.", 
"They don't ignore responsibilities.", 
"We don't arrive late to meetings.", 
"It doesn't get bright early in winter.", 
"He doesn't avoid hard work.", 
"The sun doesn't rise in the west.", 
"I don't hate public speaking.", 
"Dogs don't fear water.", 
"She doesn't dislike classical music.", 
"We don't interrupt others.", 
"It doesn't smell bad in the kitchen.", 
"He doesn't dislike helping others.", 
"They don't forget birthdays.", 
"I don't dislike camping.", 
"The kids don't hate playing outside.", 
"She doesn't wear mismatched socks.", 
"We don't dislike volunteering.", 
"The moon doesn't revolve around the Earth.", 
"I don't avoid challenges.", 
"Birds don't dislike flying.", 
"He doesn't dislike waking up early.", 
"They don't miss important events.", 
"We don't dislike family gatherings.", 
"She doesn't dislike yoga.", 
"The company doesn't discriminate.", 
"I don't dislike cleaning my room.", 
"It doesn't smell bad in the bathroom.", 
"The baby doesn't hate bath time.", 
"They don't dislike board games.", 
"We don't dislike recycling.", 
"He doesn't hate telling the truth.", 
"The train doesn't depart late.", 
"I don't dislike learning new languages.", 
"She doesn't dislike photography.", 
"They don't dislike visiting museums.", 
"We don't dislike cats.", 
"The river doesn't flood often.", 
"I don't dislike public transportation.", 
"It doesn't get cold in the summer.", 
"He doesn't dislike walking.", 
"She doesn't dislike practicing the piano.", 
"The clock doesn't tick irregularly.", 
"I don't dislike singing in public.", 
"Birds don't dislike building nests.", 
"We don't dislike watching sports.", 
"They don't dislike traveling.", 
"The baby doesn't dislike crawling.", 
"Dogs don't dislike fetch.", 
"I don't dislike gardening.", 
"The company doesn't dislike innovation.", 
"He doesn't dislike exercising.", 
"She doesn't dislike mountain climbing.", 
"We don't dislike riding bikes.", 
"It doesn't rain indoors.", 
"I don't dislike volunteering.", 
"They don't dislike exploring new places.", 
"The sun doesn't dislike giving warmth.", 
"We don't dislike studying.", 
"She doesn't dislike taking photos.", 
"It doesn't get dark in the morning.", 
"He doesn't dislike smiling."], ["Do I eat breakfast every morning?", 
"Does she play the piano beautifully?", 
"Do we live in a big house?", 
"Do they go to school together?", 
"Does he speak English fluently?", 
"Does the sun rise in the east?", 
"Do dogs bark loudly?", 
"Do birds sing in the morning?", 
"Does the Earth revolve around the sun?", 
"Do we drink coffee in the evening?", 
"Does it rain often in this city?", 
"Do I love chocolate ice cream?", 
"Does she work in an office?", 
"Do they visit their grandparents regularly?", 
"Does the train arrive at 9 AM?", 
"Does he watch movies on weekends?", 
"Do cats chase mice?", 
"Do we wear uniforms to school?", 
"Does the teacher explain the lesson?", 
"Does the river flow smoothly?", 
"Do I walk to the park every day?", 
"Does the company produce quality products?", 
"Does she like to read novels?", 
"Do they enjoy playing video games?", 
"Does the clock tick loudly?", 
"Does it snow in winter?", 
"Do we listen to music in the car?", 
"Does he brush his teeth twice a day?", 
"Does the cat sleep on the couch?", 
"Do I run in the park for exercise?", 
"Do birds build nests in trees?", 
"Does the store open at 8 AM?", 
"Does she study for exams?", 
"Do they swim in the pool?", 
"Do we drive to work together?", 
"Does the baby laugh a lot?", 
"Does he tell interesting stories?", 
"Does the computer work perfectly?", 
"Do I always forget my keys?", 
"Does she buy groceries every Sunday?", 
"Do they grow vegetables in the garden?", 
"Do we celebrate birthdays with cake?", 
"Does it get dark early in winter?", 
"Does he climb mountains for fun?", 
"Does the sun set in the west?", 
"Do I teach English to students?", 
"Do dogs wag their tails when happy?", 
"Does she play soccer after school?", 
"Do we visit the beach in the summer?", 
"Does it taste delicious?", 
"Does he exercise at the gym?", 
"Do they take the bus to work?", 
"Do I paint landscapes?", 
"Do the kids enjoy playing outside?", 
"Does she always wear a smile?", 
"Do we participate in community events?", 
"Does the moon shine at night?", 
"Do I write poems in my free time?", 
"Do birds migrate in winter?", 
"Does he fix cars for a living?", 
"Do they enjoy hiking in the mountains?", 
"Do we attend family gatherings?", 
"Does she practice yoga daily?", 
"Does the company hire new employees?", 
"Do I clean my room on weekends?", 
"Does it smell wonderful in the kitchen?", 
"Does the baby crawl on the floor?", 
"Do they play board games together?", 
"Do we recycle plastic bottles?", 
"Does he tell jokes to make people laugh?", 
"Does the train depart at 6 PM?", 
"Do I speak Spanish and English?", 
"Does she take photographs of nature?", 
"Do we visit the museum occasionally?", 
"Does the cat purr when petted?", 
"Does the river freeze in winter?", 
"Do I volunteer at the local shelter?", 
"Do they eat dinner at 7 PM?", 
"Do we walk in the park after dinner?", 
"Does she practice the piano daily?", 
"Does the clock tick loudly?", 
"Do I sing in the shower?", 
"Do birds build nests in spring?", 
"Does he enjoy watching sports?", 
"Do they visit relatives during holidays?", 
"Do we plant flowers in the garden?", 
"Does she read books before bedtime?", 
"Does it rain during the monsoon?", 
"Do I work on projects at the office?", 
"Does the children play in the playground?", 
"Do dogs fetch the ball?", 
"Do we ride bikes in the park?", 
"Does the company produce eco-friendly products?", 
"Does she exercise for good health?", 
"Do they explore new places on vacations?", 
"Do I enjoy learning new things?", 
"Does it get hot in the summer?", 
"Do we take photos on special occasions?", 
"Does the sun give us light?", 
"Does he greet everyone with a smile?"]];

const presentContinuous = [["I am eating breakfast right now.", 
"She is playing the piano beautifully.", 
"We are living in a big house.", 
"They are going to school together.", 
"He is speaking English fluently.", 
"The sun is rising in the east.", 
"Dogs are barking loudly.", 
"Birds are singing in the morning.", 
"The Earth is revolving around the sun.", 
"We are drinking coffee in the evening.", 
"It is raining often in this city.", 
"I am loving chocolate ice cream.", 
"She is working in an office.", 
"They are visiting their grandparents regularly.", 
"The train is arriving at 9 AM.", 
"He is watching movies on weekends.", 
"Cats are chasing mice.", 
"We are wearing uniforms to school.", 
"The teacher is explaining the lesson.", 
"The river is flowing smoothly.", 
"I am walking to the park every day.", 
"The company is producing quality products.", 
"She is liking to read novels.", 
"They are enjoying playing video games.", 
"The clock is ticking loudly.", 
"It is snowing in winter.", 
"We are listening to music in the car.", 
"He is brushing his teeth twice a day.", 
"The cat is sleeping on the couch.", 
"I am running in the park for exercise.", 
"Birds are building nests in trees.", 
"The store is opening at 8 AM.", 
"She is studying for exams.", 
"They are swimming in the pool.", 
"We are driving to work together.", 
"The baby is laughing a lot.", 
"He is telling interesting stories.", 
"The computer is working perfectly.", 
"I am always forgetting my keys.", 
"She is buying groceries every Sunday.", 
"They are growing vegetables in the garden.", 
"We are celebrating birthdays with cake.", 
"It is getting dark early in winter.", 
"He is climbing mountains for fun.", 
"The sun is setting in the west.", 
"I am teaching English to students.", 
"Dogs are wagging their tails when happy.", 
"She is playing soccer after school.", 
"We are visiting the beach in the summer.", 
"It is tasting delicious.", 
"He is exercising at the gym.", 
"They are taking the bus to work.", 
"I am painting landscapes.", 
"The kids are enjoying playing outside.", 
"She is always wearing a smile.", 
"We are participating in community events.", 
"The moon is shining at night.", 
"I am writing poems in my free time.", 
"Birds are migrating in winter.", 
"He is fixing cars for a living.", 
"They are enjoying hiking in the mountains.", 
"We are attending family gatherings.", 
"She is practicing yoga daily.", 
"The company is hiring new employees.", 
"I am cleaning my room on weekends.", 
"It is smelling wonderful in the kitchen.", 
"The baby is crawling on the floor.", 
"They are playing board games together.", 
"We are recycling plastic bottles.", 
"He is telling jokes to make people laugh.", 
"The train is departing at 6 PM.", 
"I am speaking Spanish and English.", 
"She is taking photographs of nature.", 
"We are visiting the museum occasionally.", 
"The cat is purring when petted.", 
"The river is freezing in winter.", 
"I am volunteering at the local shelter.", 
"They are eating dinner at 7 PM.", 
"We are walking in the park after dinner.", 
"She is practicing the piano daily.", 
"The clock is ticking loudly.", 
"I am singing in the shower.", 
"Birds are building nests in spring.", 
"He is enjoying watching sports.", 
"They are visiting relatives during holidays.", 
"We are planting flowers in the garden.", 
"She is reading books before bedtime.", 
"It is raining during the monsoon.", 
"I am working on projects at the office.", 
"The children are playing in the playground.", 
"Dogs are fetching the ball.", 
"We are riding bikes in the park.", 
"The company is producing eco-friendly products.", 
"She is exercising for good health.", 
"They are exploring new places on vacations.", 
"I am enjoying learning new things.", 
"It is getting hot in the summer.", 
"We are taking photos on special occasions.", 
"The sun is giving us light.", 
"He is greeting everyone with a smile."], ["I am not eating breakfast right now.", 
"She is not playing the piano beautifully.", 
"We are not living in a big house.", 
"They are not going to school together.", 
"He is not speaking English fluently.", 
"The sun is not rising in the east.", 
"Dogs are not barking loudly.", 
"Birds are not singing in the morning.", 
"The Earth is not revolving around the sun.", 
"We are not drinking coffee in the evening.", 
"It is not raining often in this city.", 
"I am not loving chocolate ice cream.", 
"She is not working in an office.", 
"They are not visiting their grandparents regularly.", 
"The train is not arriving at 9 AM.", 
"He is not watching movies on weekends.", 
"Cats are not chasing mice.", 
"We are not wearing uniforms to school.", 
"The teacher is not explaining the lesson.", 
"The river is not flowing smoothly.", 
"I am not walking to the park every day.", 
"The company is not producing quality products.", 
"She is not liking to read novels.", 
"They are not enjoying playing video games.", 
"The clock is not ticking loudly.", 
"It is not snowing in winter.", 
"We are not listening to music in the car.", 
"He is not brushing his teeth twice a day.", 
"The cat is not sleeping on the couch.", 
"I am not running in the park for exercise.", 
"Birds are not building nests in trees.", 
"The store is not opening at 8 AM.", 
"She is not studying for exams.", 
"They are not swimming in the pool.", 
"We are not driving to work together.", 
"The baby is not laughing a lot.", 
"He is not telling interesting stories.", 
"The computer is not working perfectly.", 
"I am not always forgetting my keys.", 
"She is not buying groceries every Sunday.", 
"They are not growing vegetables in the garden.", 
"We are not celebrating birthdays with cake.", 
"It is not getting dark early in winter.", 
"He is not climbing mountains for fun.", 
"The sun is not setting in the west.", 
"I am not teaching English to students.", 
"Dogs are not wagging their tails when happy.", 
"She is not playing soccer after school.", 
"We are not visiting the beach in the summer.", 
"It is not tasting delicious.", 
"He is not exercising at the gym.", 
"They are not taking the bus to work.", 
"I am not painting landscapes.", 
"The kids are not enjoying playing outside.", 
"She is not always wearing a smile.", 
"We are not participating in community events.", 
"The moon is not shining at night.", 
"I am not writing poems in my free time.", 
"Birds are not migrating in winter.", 
"He is not fixing cars for a living.", 
"They are not enjoying hiking in the mountains.", 
"We are not attending family gatherings.", 
"She is not practicing yoga daily.", 
"The company is not hiring new employees.", 
"I am not cleaning my room on weekends.", 
"It is not smelling wonderful in the kitchen.", 
"The baby is not crawling on the floor.", 
"They are not playing board games together.", 
"We are not recycling plastic bottles.", 
"He is not telling jokes to make people laugh.", 
"The train is not departing at 6 PM.", 
"I am not speaking Spanish and English.", 
"She is not taking photographs of nature.", 
"We are not visiting the museum occasionally.", 
"The cat is not purring when petted.", 
"The river is not freezing in winter.", 
"I am not volunteering at the local shelter.", 
"They are not eating dinner at 7 PM.", 
"We are not walking in the park after dinner.", 
"She is not practicing the piano daily.", 
"The clock is not ticking loudly.", 
"I am not singing in the shower.", 
"Birds are not building nests in spring.", 
"He is not enjoying watching sports.", 
"They are not visiting relatives during holidays.", 
"We are not planting flowers in the garden.", 
"She is not reading books before bedtime.", 
"It is not raining during the monsoon.", 
"I am not working on projects at the office.", 
"The children are not playing in the playground.", 
"Dogs are not fetching the ball.", 
"We are not riding bikes in the park.", 
"The company is not producing eco-friendly products.", 
"She is not exercising for good health.", 
"They are not exploring new places on vacations.", 
"I am not enjoying learning new things.", 
"It is not getting hot in the summer.", 
"We are not taking photos on special occasions.", 
"The sun is not giving us light.", 
"He is not greeting everyone with a smile."], ["Am I eating breakfast right now?", 
"Is she playing the piano beautifully?", 
"Are we living in a big house?", 
"Are they going to school together?", 
"Is he speaking English fluently?", 
"Is the sun rising in the east?", 
"Are dogs barking loudly?", 
"Are birds singing in the morning?", 
"Is the Earth revolving around the sun?", 
"Are we drinking coffee in the evening?", 
"Is it raining often in this city?", 
"Am I loving chocolate ice cream?", 
"Is she working in an office?", 
"Are they visiting their grandparents regularly?", 
"Is the train arriving at 9 AM?", 
"Is he watching movies on weekends?", 
"Are cats chasing mice?", 
"Are we wearing uniforms to school?", 
"Is the teacher explaining the lesson?", 
"Is the river flowing smoothly?", 
"Am I walking to the park every day?", 
"Is the company producing quality products?", 
"Is she liking to read novels?", 
"Are they enjoying playing video games?", 
"Is the clock ticking loudly?", 
"Is it snowing in winter?", 
"Are we listening to music in the car?", 
"Is he brushing his teeth twice a day?", 
"Is the cat sleeping on the couch?", 
"Am I running in the park for exercise?", 
"Are birds building nests in trees?", 
"Is the store opening at 8 AM?", 
"Is she studying for exams?", 
"Are they swimming in the pool?", 
"Are we driving to work together?", 
"Is the baby laughing a lot?", 
"Is he telling interesting stories?", 
"Is the computer working perfectly?", 
"Am I always forgetting my keys?", 
"Is she buying groceries every Sunday?", 
"Are they growing vegetables in the garden?", 
"Are we celebrating birthdays with cake?", 
"Is it getting dark early in winter?", 
"Is he climbing mountains for fun?", 
"Is the sun setting in the west?", 
"Am I teaching English to students?", 
"Are dogs wagging their tails when happy?", 
"Is she playing soccer after school?", 
"Are we visiting the beach in the summer?", 
"Is it tasting delicious?", 
"Is he exercising at the gym?", 
"Are they taking the bus to work?", 
"Am I painting landscapes?", 
"Are the kids enjoying playing outside?", 
"Is she always wearing a smile?", 
"Are we participating in community events?", 
"Is the moon shining at night?", 
"Am I writing poems in my free time?", 
"Are birds migrating in winter?", 
"Is he fixing cars for a living?", 
"Are they enjoying hiking in the mountains?", 
"Are we attending family gatherings?", 
"Is she practicing yoga daily?", 
"Is the company hiring new employees?", 
"Am I cleaning my room on weekends?", 
"Is it smelling wonderful in the kitchen?", 
"Is the baby crawling on the floor?", 
"Are they playing board games together?", 
"Are we recycling plastic bottles?", 
"Is he telling jokes to make people laugh?", 
"Is the train departing at 6 PM?", 
"Am I speaking Spanish and English?", 
"Is she taking photographs of nature?", 
"Are we visiting the museum occasionally?", 
"Is the cat purring when petted?", 
"Is the river freezing in winter?", 
"Am I volunteering at the local shelter?", 
"Are they eating dinner at 7 PM?", 
"Are we walking in the park after dinner?", 
"Is she practicing the piano daily?", 
"Is the clock ticking loudly?", 
"Am I singing in the shower?", 
"Are birds building nests in spring?", 
"Is he enjoying watching sports?", 
"Are they visiting relatives during holidays?", 
"Are we planting flowers in the garden?", 
"Is she reading books before bedtime?", 
"Is it raining during the monsoon?", 
"Am I working on projects at the office?", 
"Are the children playing in the playground?", 
"Are dogs fetching the ball?", 
"Are we riding bikes in the park?", 
"Is the company producing eco-friendly products?", 
"Is she exercising for good health?", 
"Are they exploring new places on vacations?", 
"Am I enjoying learning new things?", 
"Is it getting hot in the summer?", 
"Are we taking photos on special occasions?", 
"Is the sun giving us light?", 
"Is he greeting everyone with a smile?"]];

const pastSimple = [["I ate breakfast an hour ago.", 
"She played the piano beautifully at the concert.", 
"We lived in a big house when I was a child.", 
"They went to school together yesterday.", 
"He spoke English fluently during the presentation.", 
"The sun rose in the east this morning.", 
"Dogs barked loudly when the mailman arrived.", 
"Birds sang in the morning, creating a pleasant melody.", 
"The Earth revolved around the sun for millions of years.", 
"We drank coffee in the evening last night.", 
"It rained often in that city last year.", 
"I loved chocolate ice cream when I was a kid.", 
"She worked in an office for several years.", 
"They visited their grandparents regularly in the past.", 
"The train arrived at 9 AM on time.", 
"He watched movies on weekends during college.", 
"Cats chased mice in the backyard.", 
"We wore uniforms to school when we were younger.", 
"The teacher explained the lesson yesterday.", 
"The river flowed smoothly through the valley.", 
"I walked to the park every day last summer.", 
"The company produced quality products in the past.", 
"She liked to read novels in her free time.", 
"They enjoyed playing video games during weekends.", 
"The clock ticked loudly in the old house.", 
"It snowed heavily last winter.", 
"We listened to music in the car on road trips.", 
"He brushed his teeth twice a day for good dental hygiene.", 
"The cat slept on the couch for hours.", 
"I ran in the park for exercise yesterday.", 
"Birds built nests in the trees during spring.", 
"The store opened at 8 AM every day.", 
"She studied for exams diligently.", 
"They swam in the pool during the hot summer days.", 
"We drove to work together last month.", 
"The baby laughed a lot during the family gathering.", 
"He told interesting stories around the campfire.", 
"The computer worked perfectly before the upgrade.", 
"I always remembered my keys in the past.", 
"She bought groceries every Sunday.", 
"They grew vegetables in the garden last year.", 
"We celebrated birthdays with cake and balloons.", 
"It got dark early in winter.", 
"He climbed mountains for fun during his youth.", 
"The sun set in the west as usual.", 
"I taught English to students for several years.", 
"Dogs wagged their tails when happy.", 
"She played soccer after school in high school.", 
"We visited the beach in the summer vacation.", 
"It tasted delicious, just like I remembered.", 
"He exercised at the gym regularly.", 
"They took the bus to work every day.", 
"I painted landscapes during my art class.", 
"The kids enjoyed playing outside in the backyard.", 
"She always wore a smile on her face.", 
"We participated in community events last year.", 
"The moon shone brightly at night.", 
"I wrote poems in my free time as a hobby.", 
"Birds migrated in winter, filling the sky.", 
"He fixed cars for a living for many years.", 
"They enjoyed hiking in the mountains every summer.", 
"We attended family gatherings during holidays.", 
"She practiced yoga daily for health benefits.", 
"The company hired new employees recently.", 
"I cleaned my room on weekends.", 
"It smelled wonderful in the kitchen during dinner.", 
"The baby crawled on the floor, exploring the room.", 
"They played board games together during the weekend.", 
"We recycled plastic bottles regularly.", 
"He told jokes to make people laugh at the party.", 
"The train departed at 6 PM on schedule.", 
"I spoke both Spanish and English fluently.", 
"She took photographs of nature during the trip.", 
"We visited the museum occasionally for cultural enrichment.", 
"The cat purred when petted gently.", 
"The river froze in winter, creating a beautiful scene.", 
"I volunteered at the local shelter to help animals.", 
"They ate dinner at 7 PM every day.", 
"We walked in the park after dinner.", 
"She practiced the piano daily to improve her skills.", 
"The clock ticked loudly in the old house.", 
"I sang in the shower, not caring who heard.", 
"Birds built nests in the spring, preparing for new life.", 
"He enjoyed watching sports on television.", 
"They visited relatives during the holidays.", 
"We planted flowers in the garden last spring.", 
"She read books before bedtime every night.", 
"It rained during the monsoon season.", 
"I worked on projects at the office for many years.", 
"The children played in the playground after school.", 
"Dogs fetched the ball with enthusiasm.", 
"We rode bikes in the park on sunny days.", 
"The company produced eco-friendly products in the past.", 
"She exercised for good health regularly.", 
"They explored new places on vacations every year.", 
"I enjoyed learning new things during my courses.", 
"It got hot in the summer, so we went to the beach.", 
"We took photos on special occasions.", 
"The sun gave us light every day.", 
"He greeted everyone with a smile, creating a positive atmosphere."], ["I did not eat breakfast an hour ago.", 
"She did not play the piano at the concert.", 
"We did not live in a big house when I was a child.", 
"They did not go to school together yesterday.", 
"He did not speak English fluently during the presentation.", 
"The sun did not rise in the east this morning.", 
"Dogs did not bark loudly when the mailman arrived.", 
"Birds did not sing in the morning, creating a pleasant melody.", 
"The Earth did not revolve around the sun for millions of years.", 
"We did not drink coffee in the evening last night.", 
"It did not rain often in that city last year.", 
"I did not love chocolate ice cream when I was a kid.", 
"She did not work in an office for several years.", 
"They did not visit their grandparents regularly in the past.", 
"The train did not arrive at 9 AM on time.", 
"He did not watch movies on weekends during college.", 
"Cats did not chase mice in the backyard.", 
"We did not wear uniforms to school when we were younger.", 
"The teacher did not explain the lesson yesterday.", 
"The river did not flow smoothly through the valley.", 
"I did not walk to the park every day last summer.", 
"The company did not produce quality products in the past.", 
"She did not like to read novels in her free time.", 
"They did not enjoy playing video games during weekends.", 
"The clock did not tick loudly in the old house.", 
"It did not snow heavily last winter.", 
"We did not listen to music in the car on road trips.", 
"He did not brush his teeth twice a day for good dental hygiene.", 
"The cat did not sleep on the couch for hours.", 
"I did not run in the park for exercise yesterday.", 
"Birds did not build nests in the trees during spring.", 
"The store did not open at 8 AM every day.", 
"She did not study for exams diligently.", 
"They did not swim in the pool during the hot summer days.", 
"We did not drive to work together last month.", 
"The baby did not laugh a lot during the family gathering.", 
"He did not tell interesting stories around the campfire.", 
"The computer did not work perfectly before the upgrade.", 
"I did not always remember my keys in the past.", 
"She did not buy groceries every Sunday.", 
"They did not grow vegetables in the garden last year.", 
"We did not celebrate birthdays with cake and balloons.", 
"It did not get dark early in winter.", 
"He did not climb mountains for fun during his youth.", 
"The sun did not set in the west as usual.", 
"I did not teach English to students for several years.", 
"Dogs did not wag their tails when happy.", 
"She did not play soccer after school in high school.", 
"We did not visit the beach in the summer vacation.", 
"It did not taste delicious, just like I remembered.", 
"He did not exercise at the gym regularly.", 
"They did not take the bus to work every day.", 
"I did not paint landscapes during my art class.", 
"The kids did not enjoy playing outside in the backyard.", 
"She did not always wear a smile on her face.", 
"We did not participate in community events last year.", 
"The moon did not shine brightly at night.", 
"I did not write poems in my free time as a hobby.", 
"Birds did not migrate in winter, filling the sky.", 
"He did not fix cars for a living for many years.", 
"They did not enjoy hiking in the mountains every summer.", 
"We did not attend family gatherings during holidays.", 
"She did not practice yoga daily for health benefits.", 
"The company did not hire new employees recently.", 
"I did not clean my room on weekends.", 
"It did not smell wonderful in the kitchen during dinner.", 
"The baby did not crawl on the floor, exploring the room.", 
"They did not play board games together during the weekend.", 
"We did not recycle plastic bottles regularly.", 
"He did not tell jokes to make people laugh at the party.", 
"The train did not depart at 6 PM on schedule.", 
"I did not speak both Spanish and English fluently.", 
"She did not take photographs of nature during the trip.", 
"We did not visit the museum occasionally for cultural enrichment.", 
"The cat did not purr when petted gently.", 
"The river did not freeze in winter, creating a beautiful scene.", 
"I did not volunteer at the local shelter to help animals.", 
"They did not eat dinner at 7 PM every day.", 
"We did not walk in the park after dinner.", 
"She did not practice the piano daily to improve her skills.", 
"The clock did not tick loudly in the old house.", 
"I did not sing in the shower, not caring who heard.", 
"Birds did not build nests in the spring, preparing for new life.", 
"He did not enjoy watching sports on television.", 
"They did not visit relatives during the holidays.", 
"We did not plant flowers in the garden last spring.", 
"She did not read books before bedtime every night.", 
"It did not rain during the monsoon season.", 
"I did not work on projects at the office for many years.", 
"The children did not play in the playground after school.", 
"Dogs did not fetch the ball with enthusiasm.", 
"We did not ride bikes in the park on sunny days.", 
"The company did not produce eco-friendly products in the past.", 
"She did not exercise for good health regularly.", 
"They did not explore new places on vacations every year.", 
"I did not enjoy learning new things during my courses.", 
"It did not get hot in the summer, so we went to the beach.", 
"We did not take photos on special occasions.", 
"The sun did not give us light every day.", 
"He did not greet everyone with a smile, creating a positive atmosphere."], ["Did I eat breakfast an hour ago?", 
"Did she play the piano at the concert?", 
"Did we live in a big house when I was a child?", 
"Did they go to school together yesterday?", 
"Did he speak English fluently during the presentation?", 
"Did the sun rise in the east this morning?", 
"Did dogs bark loudly when the mailman arrived?", 
"Did birds sing in the morning, creating a pleasant melody?", 
"Did the Earth revolve around the sun for millions of years?", 
"Did we drink coffee in the evening last night?", 
"Did it rain often in that city last year?", 
"Did I love chocolate ice cream when I was a kid?", 
"Did she work in an office for several years?", 
"Did they visit their grandparents regularly in the past?", 
"Did the train arrive at 9 AM on time?", 
"Did he watch movies on weekends during college?", 
"Did cats chase mice in the backyard?", 
"Did we wear uniforms to school when we were younger?", 
"Did the teacher explain the lesson yesterday?", 
"Did the river flow smoothly through the valley?", 
"Did I walk to the park every day last summer?", 
"Did the company produce quality products in the past?", 
"Did she like to read novels in her free time?", 
"Did they enjoy playing video games during weekends?", 
"Did the clock tick loudly in the old house?", 
"Did it snow heavily last winter?", 
"Did we listen to music in the car on road trips?", 
"Did he brush his teeth twice a day for good dental hygiene?", 
"Did the cat sleep on the couch for hours?", 
"Did I run in the park for exercise yesterday?", 
"Did birds build nests in the trees during spring?", 
"Did the store open at 8 AM every day?", 
"Did she study for exams diligently?", 
"Did they swim in the pool during the hot summer days?", 
"Did we drive to work together last month?", 
"Did the baby laugh a lot during the family gathering?", 
"Did he tell interesting stories around the campfire?", 
"Did the computer work perfectly before the upgrade?", 
"Did I always remember my keys in the past?", 
"Did she buy groceries every Sunday?", 
"Did they grow vegetables in the garden last year?", 
"Did we celebrate birthdays with cake and balloons?", 
"Did it get dark early in winter?", 
"Did he climb mountains for fun during his youth?", 
"Did the sun set in the west as usual?", 
"Did I teach English to students for several years?", 
"Did dogs wag their tails when happy?", 
"Did she play soccer after school in high school?", 
"Did we visit the beach in the summer vacation?", 
"Did it taste delicious, just like I remembered?", 
"Did he exercise at the gym regularly?", 
"Did they take the bus to work every day?", 
"Did I paint landscapes during my art class?", 
"Did the kids enjoy playing outside in the backyard?", 
"Did she always wear a smile on her face?", 
"Did we participate in community events last year?", 
"Did the moon shine brightly at night?", 
"Did I write poems in my free time as a hobby?", 
"Did birds migrate in winter, filling the sky?", 
"Did he fix cars for a living for many years?", 
"Did they enjoy hiking in the mountains every summer?", 
"Did we attend family gatherings during holidays?", 
"Did she practice yoga daily for health benefits?", 
"Did the company hire new employees recently?", 
"Did I clean my room on weekends?", 
"Did it smell wonderful in the kitchen during dinner?", 
"Did the baby crawl on the floor, exploring the room?", 
"Did they play board games together during the weekend?", 
"Did we recycle plastic bottles regularly?", 
"Did he tell jokes to make people laugh at the party?", 
"Did the train depart at 6 PM on schedule?", 
"Did I speak both Spanish and English fluently?", 
"Did she take photographs of nature during the trip?", 
"Did we visit the museum occasionally for cultural enrichment?", 
"Did the cat purr when petted gently?", 
"Did the river freeze in winter, creating a beautiful scene?", 
"Did I volunteer at the local shelter to help animals?", 
"Did they eat dinner at 7 PM every day?", 
"Did we walk in the park after dinner?", 
"Did she practice the piano daily to improve her skills?", 
"Did the clock tick loudly in the old house?", 
"Did I sing in the shower, not caring who heard?", 
"Did birds build nests in the spring, preparing for new life?", 
"Did he enjoy watching sports on television?", 
"Did they visit relatives during the holidays?", 
"Did we plant flowers in the garden last spring?", 
"Did she read books before bedtime every night?", 
"Did it rain during the monsoon season?", 
"Did I work on projects at the office for many years?", 
"Did the children play in the playground after school?", 
"Did dogs fetch the ball with enthusiasm?", 
"Did we ride bikes in the park on sunny days?", 
"Did the company produce eco-friendly products in the past?", 
"Did she exercise for good health regularly?", 
"Did they explore new places on vacations every year?", 
"Did I enjoy learning new things during my courses?", 
"Did it get hot in the summer, so we went to the beach?", 
"Did we take photos on special occasions?", 
"Did the sun give us light every day?", 
"Did he greet everyone with a smile, creating a positive atmosphere?"]];




let right = 0;
let notRight = 0;

function refreshScore () {
    document.getElementById('right').innerHTML = `Правильно: ${right}`;
    document.getElementById('not-right').innerHTML = `Неправильно: ${notRight}`;
}

const randomSentences = document.getElementById('random-sentences');
let randomS = 0;

function getSentences () {
    let randomN = Math.floor(Math.random() * 100);
    let randomNn = Math.floor(Math.random() * 3);
    randomS = Math.floor(Math.random() * 3);

    if (randomS === 0) {
        randomSentences.innerHTML = presentSimple[randomNn][randomN];
    } else if (randomS === 1) {
        randomSentences.innerHTML = presentContinuous[randomNn][randomN];
    } else if (randomS === 2) {
        randomSentences.innerHTML = pastSimple[randomNn][randomN];
    } else {
        randomSentences.innerHTML = 'Something wrong!';
    }
}

const radioButtons = document.querySelectorAll('input[name="mode"]');

function checkButton () {
    let selectedSize;
    for (const radioButton of radioButtons) {
      if (radioButton.checked) {
        selectedSize = radioButton.value;
        break;
      }
    }
    return selectedSize;
}

function checkAnswer (val) {
    if (val === "present-simple" && randomS === 0) {
        console.log("You win, it's Present Simple!");
        right++;
    } else if (val === "present-continuous" && randomS === 1) {
        console.log("You win, it's Present Perfect!");
        right++;
    } else if (val === "past-simple" && randomS === 2) {
        console.log("You win, it's Past Simple!");
        right++;
    } else {
        console.log("You lose");
        notRight++;
    }
    getSentences();
    refreshScore();
}

getSentences();